### ISSUE TITLE
Dockfile构建需要升级Docker版本，提供下centos的升级方式

### ISSUE THREAD

**Issue by rayepeng** [zema1/watchvuln#16]
卸载旧版本的docker

```bash
sudo yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine
```

安装社区版

```bash
sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install docker-ce docker-ce-cli containerd.io
```

安装

```bash
sudo yum install docker-ce-<VERSION_STRING> docker-ce-cli-<VERSION_STRING> containerd.io
```

启动服务

```bash
sudo systemctl start docker
```

升级到最新版的docker就能构建Dockerfile了，另外个人更喜欢用 `docker-compose.yml` 的方式，提供一份

```yaml
version: '3'
services:
  watchvuln:
    build: .
    environment:
      - DINGDING_ACCESS_TOKEN=""
      - DINGDING_SECRET=""
      - WECHATWORK_KEY=""
```
